machine: "ks"

base_model: "intern_vl_8b"

clip_diffusion_connector:
  clip_dim: 1024

train:
  root: null
  resume_path: null
  global_step: 0

  exp_name: &exp_name "sana_1024"
  wandb_proj: *exp_name
  output_dir: "0812_dev"
  logging_dir: "logs"
  mixed_precision: "bf16"
  gradient_accumulation_steps: 1
  report_to: "wandb"

  lr: 1e-4
  num_iter: 200000
  save_every: 5000

data:
  wds_path: ["/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Long-Caption", "/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Short-Caption", "/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-JourneyDB"]
  img_size: 448
  buffer_size: 50000
  batch_size: 64
  num_workers: 8
  num_img_token: 1024
  max_seq_length: 1276
  cfg_drop_rate: 0.1