machine: "ks"

base_model: "intern_vl_8b"

train:
  root: null
  resume_path: "/data/phd/jinjiachun/experiment/mmdit/0813_sd3_1024/mmdit-mmdit-90000"
  global_step: 90000

  exp_name: &exp_name "mmdit"
  wandb_proj: *exp_name
  output_dir: "0813_sd3_1024"
  logging_dir: "logs"
  mixed_precision: "bf16"
  gradient_accumulation_steps: 1
  report_to: "wandb"

  lr: 1e-4
  num_iter: 400000
  save_every: 5000

data:
  wds_path: ["/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Long-Caption", "/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Short-Caption", "/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-JourneyDB"]
  img_size: 448
  buffer_size: 50000
  batch_size: 16
  num_workers: 8
  num_img_token: 1024
  max_seq_length: 1276
  cfg_drop_rate: 0.1