machine: ks

hybrid_dit:
  condition_injection: beginning
  intern_hidden_size: 1536
  hidden_size: 1024
  num_heads: 16
  depth: 16
  seq_len: 1024
  block_size: 4
  out_channels: 1024

train:
  root: null
  resume_path: null
  global_step: 0

  exp_name: &exp_name clip_dit
  wandb_proj: *exp_name
  output_dir: 0818_intern_hybrid
  logging_dir: logs
  mixed_precision: bf16
  gradient_accumulation_steps: 1
  report_to: null

  lr: 1e-4
  num_iter: 200000
  save_every: 5000

data:
  wds_path: [/data/phd/jinjiachun/dataset/timm/imagenet-1k-wds]
  num_train_examples: 1331167
  img_size: 448
  buffer_size: 50000
  batch_size: 50
  num_workers: 8
  cfg_drop_rate: 0.1