machine: "ks" # [g3, ks]

vae_aligner:
  pretrained_path: "/data/phd/jinjiachun/experiment/vae_aligner/0714_sd3_vae_aligner_hybrid/vae_aligner-vae_aligner-51k"
  # pretrained_path: "/data1/jjc/experiment/vae_aligner/0714_sd3_vae_aligner_hybrid/vae_aligner-vae_aligner-6k"
  hidden_size: 1024
  depth: 16
  num_heads: 16
  grid_size: 24

  siglip_feature_dim: 1024
  siglip_feature_dim_down: 16

diffhead:
  hidden_size: 1024
  depth: 2
  x_dim: 16
  z_dim: 2048

tune_backbone: true

train:
  root:
  diffhead_resume_path: "/data/phd/jinjiachun/experiment/query_dit/0717_diff_head_fixbackbone_ar/diff_head-query_dit-120000"
  siglip16_aligner_resume_path: "/data/phd/jinjiachun/experiment/query_dit/0717_diff_head_fixbackbone_ar/siglip16_aligner-query_dit-120000"
  backbone_resume_path:
  skipped_keys:
  global_step: 0

  ar_backbone: "janus1b" # [janus1b, janus7b]
  gen_feature: "siglip16" # [vae, siglip16]

  exp_name: &exp_name "query_dit"
  wandb_proj: *exp_name
  output_dir: "0723_mix"
  logging_dir: "logs"
  mixed_precision: "bf16"
  gradient_accumulation_steps: 1
  report_to: "wandb"

  cfg_drop_rate: 0.1

  lr: 1e-4
  num_iter: 100000
  save_every: 5000


data:
  name: "t2i"
  train_path:
  batch_size: 20
  num_workers: 8
  img_size: 384
  streaming: true
  buffer_size: 80000
  max_text_length: 192