machine: "ks" # [g4, ks]

train:
  root:
  global_step: 0

  exp_name: &exp_name "query_dit"
  wandb_proj: *exp_name
  output_dir: "0728_hybrid_dataloader_test"
  logging_dir: "logs"
  mixed_precision: "bf16"
  gradient_accumulation_steps: 1
  report_to: "no"
  num_iter: 1000000


data:
  name: "hybrid"
  understanding:
    img_path: "/data/phd/jinjiachun/dataset/llava_mix665k"
    ann_path: "/data/phd/jinjiachun/dataset/liuhaotian/LLaVA-Instruct-150K/llava_v1_5_mix665k.json"
    batch_size: 100
    num_workers: 32
  generation:
    wds_path: ["/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Long-Caption", "/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Short-Caption"]
    img_size: 384
    buffer_size: 10000
    batch_size: 50
    num_workers: 32
  max_seq_length: 1024
  num_img_token: 576