machine: "ks" # [g3, ks]

vae_aligner:
  pretrained_path: "/data/phd/jinjiachun/experiment/vae_aligner/0706_vae_aligner_hybrid_50M/vae_aligner-vae_aligner-190k"
  hidden_size: 1024
  depth: 16
  num_heads: 16
  grid_size: 24

  siglip_feature_dim: 1024
  siglip_feature_dim_down: 16

query_dit:
  hidden_size: 1024
  num_heads: 16
  depth: 16
  x_dim: 16
  z_dim: 2048

query:
  num_queries: 576
  query_dim: 2048

train:
  root:
  resume_path:
  skipped_keys:
  global_step:

  exp_name: &exp_name "query"
  wandb_proj: *exp_name
  output_dir: "0707_query"
  logging_dir: "logs"
  mixed_precision: "bf16"
  gradient_accumulation_steps: 1
  report_to: "no"

  cfg_drop_rate: 0.1

  lr: 1e-4
  num_iter: 500000
  save_every: 5000


data:
  name: "t2i"
  train_path:
  batch_size: 32
  num_workers: 8
  img_size: 384
  streaming: true
  max_text_length: 192