machine: ks
# --------------------------------------------------
model:
  internvl_path: /data/phd/jinjiachun/ckpt/OpenGVLab/InternVL3-8B
  clip_feature_dim: 4096
  diffhead:
    hidden_size: 3584
    depth: 2
    x_dim: 16
    z_dim: 3584
# --------------------------------------------------
train:
  root: null
  resume_path: null
  global_step: 0

  exp_name: &exp_name pos
  wandb_proj: *exp_name
  output_dir: 0905_joint_proj
  logging_dir: logs
  mixed_precision: bf16
  gradient_accumulation_steps: 1
  report_to: wandb

  lr: 1e-4
  num_iter: 500000
  save_every: 5000
# --------------------------------------------------
data:
  wds_path: [/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Long-Caption, /data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Short-Caption, /data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-JourneyDB]
  use_template: true
  num_train_examples: 35000000
  img_size: 448
  buffer_size: 50
  batch_size: 16
  num_workers: 8
  cfg_drop_rate: 0.1
  num_img_token: 256
  max_seq_length: 512