machine: "ks"

vae_aligner:
  hidden_size: 1536
  depth: 16
  num_heads: 24
  grid_size: 16
  scale_factor: 1.75

  siglip_feature_dim: 896
  siglip_feature_dim_down: 8

train:
  root: null
  resume_path: "/data/phd/jinjiachun/experiment/intern_clip/0805_intern_aligner/vae_aligner-intern_clip-4666"
  global_step: 4666

  exp_name: &exp_name "intern_clip"
  wandb_proj: *exp_name
  output_dir: "0805_intern_aligner"
  logging_dir: "logs"
  mixed_precision: "bf16"
  gradient_accumulation_steps: 1
  report_to: "wandb"

  lr: 1e-4
  num_iter: 100000
  save_every: 2000

data:
  # wds_path: ["/data/phd/jinjiachun/dataset/timm/imagenet-1k-wds/"]
  wds_path: ["/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Long-Caption", "/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Short-Caption", "/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-JourneyDB",]
  img_size: 448
  buffer_size: 30000
  batch_size: 100
  num_workers: 8