machine: "ks" # [g3, ks]

vae_aligner:
  hidden_size: 1024
  depth: 16
  num_heads: 16
  grid_size: 24

  siglip_feature_dim: 1024
  siglip_feature_dim_down: 16

train:
  root:
  resume_path: "/data/phd/jinjiachun/experiment/vae_aligner/0714_sd3_vae_aligner_hybrid/vae_aligner-vae_aligner-51k"
  skipped_keys:
  global_step: 51000

  exp_name: &exp_name "vae_aligner"
  wandb_proj: *exp_name
  output_dir: "0714_sd3_vae_aligner_hybrid"
  logging_dir: "logs"
  mixed_precision: "bf16"
  gradient_accumulation_steps: 1
  report_to: "wandb"

  lr: 1e-4
  num_iter: 100000
  save_every: 5000

data:
  name: "hybrid"
  train_path:
  batch_size: 150
  num_workers: 8
  img_size: 384
  streaming: true
  buffer_size: 80000
  max_text_length: 192