machine: ks
# --------------------------------------------------
model:
  internvl_path: /data/phd/jinjiachun/ckpt/OpenGVLab/InternVL3-2B
  clip_feature_dim: 4096
  diffhead:
    hidden_size: &z_dim 1536
    depth: 2
    x_dim: 16
    z_dim: *z_dim
  mmdit:
    context_dim: 16
    sd3_5_path: /data/phd/jinjiachun/ckpt/stabilityai/stable-diffusion-3.5-medium
    load_pretrained: false
  hp_ar: 10
  hp_dit: 1
# --------------------------------------------------
train:
  root: null
  resume_path: /data/phd/jinjiachun/experiment/pos/0908_joint_proj_2b_vf_xgen_context_query_hat/internvl-pos-46000
  global_step: 46000

  exp_name: &exp_name pos
  wandb_proj: *exp_name
  output_dir: 0908_rec_only
  logging_dir: logs
  mixed_precision: bf16
  gradient_accumulation_steps: 1
  report_to: null

  lr: 1e-4
  num_iter: 500000
  save_every: 1000
# --------------------------------------------------
data:
  wds_path: [/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Long-Caption, /data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Short-Caption, /data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-JourneyDB]
  use_template: false
  num_train_examples: 35000000
  img_size: 448
  buffer_size: 50000
  batch_size: 20
  num_workers: 8
  cfg_drop_rate: 0.0
  num_img_token: 256
  max_seq_length: 512