machine: "ks"

feature_down_projector:
  clip_feature_dim: 1024
  feature_dim_output: 64
  ckpt_path: /data/phd/jinjiachun/experiment/mmdit/0811_1024x64/mmdit-mmdit-30000

model:
  diffhead:
    hidden_size: 1024
    depth: 2
    x_dim: 64
    z_dim: 896
    # z_dim: 1536

  tune_backbone: true

base_model: "intern_vl_1b"
# base_model: "intern_vl_2b"

train:
  root: null
  diffhead_resume_path: null
  clip_projector_resume_path: null
  backbone_resume_path: null
  global_step: 0

  exp_name: &exp_name "intern_gen"
  wandb_proj: *exp_name
  output_dir: "0811_aligner_free_1b"
  logging_dir: "logs"
  mixed_precision: "bf16"
  gradient_accumulation_steps: 1
  report_to: "no"

  lr: 1e-4
  num_iter: 100000
  save_every: 1000

data:
  wds_path: ["/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Long-Caption", "/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Short-Caption", "/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-JourneyDB",]
  img_size: 448
  buffer_size: 500
  batch_size: 8
  num_workers: 8
  num_img_token: 1024
  max_seq_length: 1280
  cfg_drop_rate: 0.1