machine: ks

ar_clip:
  in_channels: 1024
  out_channels: 2048
  num_tokens: 1024

  hidden_size: 2048
  num_heads: 16
  depth: 16

  num_classes: 1000

  diff_head:
    hidden_size: 2048
    depth: 2
    x_dim: 1024
    z_dim: 2048

train:
  root: null
  resume_path: null
  global_step: 0

  exp_name: &exp_name clip_dit
  wandb_proj: *exp_name
  output_dir: 0815_ar_clip
  logging_dir: logs
  mixed_precision: bf16
  gradient_accumulation_steps: 1
  report_to: wandb

  lr: 1e-4
  num_iter: 200000
  save_every: 5000

data:
  wds_path: [/data/phd/jinjiachun/dataset/timm/imagenet-1k-wds]
  num_train_examples: 1331167
  img_size: 448
  buffer_size: 50000
  batch_size: 50
  num_workers: 8
  cfg_drop_rate: 0.1