machine: ks

dit:
  in_channels: 1024
  out_channels: 1024
  num_tokens: 1024

  hidden_size: 2048
  num_heads: 32
  depth: 32

  num_classes: 1000

  # repa:
  #   depth: 4

train:
  root: null
  resume_path: "/data/phd/jinjiachun/experiment/clip_1024/0823_imagenet_holistic_diffusion_32_32_2048_repa_4/dit-clip_1024-190000"
  global_step: 190000

  exp_name: &exp_name clip_1024
  wandb_proj: *exp_name
  output_dir: 0823_imagenet_holistic_diffusion_32_32_2048_repa_4
  logging_dir: logs
  mixed_precision: bf16
  gradient_accumulation_steps: 1
  report_to: wandb

  lr: 1e-4
  num_iter: 500000
  save_every: 5000

data:
  wds_path: [/data/phd/jinjiachun/dataset/timm/imagenet-1k-wds]
  num_train_examples: 1331167
  img_size: 448
  buffer_size: 70000
  batch_size: 19
  num_workers: 8
  cfg_drop_rate: 0.1