machine: ks

dit:
  in_channels: 1024
  out_channels: 1024
  num_tokens: 1024

  hidden_size: 1536
  num_heads: 24
  depth: 24

  num_classes: 1000

train:
  root: null
  resume_path: "/data/phd/jinjiachun/experiment/clip_1024/0822_imagenet_holistic_diffusion/dit-clip_1024-25000"
  global_step: 25000

  exp_name: &exp_name clip_1024
  wandb_proj: *exp_name
  output_dir: 0822_imagenet_holistic_diffusion
  logging_dir: logs
  mixed_precision: bf16
  gradient_accumulation_steps: 1
  report_to: wandb

  lr: 1e-4
  num_iter: 200000
  save_every: 5000

data:
  wds_path: [/data/phd/jinjiachun/dataset/timm/imagenet-1k-wds]
  num_train_examples: 1331167
  img_size: 448
  buffer_size: 70000
  batch_size: 40
  num_workers: 8
  cfg_drop_rate: 0.1