machine: ks

model:
  num_hat: 1
  dit_head:
    in_channels: 1024
    out_channels: 1024
    condition_channels: 3584
    num_tokens: 4

    hidden_size: 2048
    num_heads: 32
    depth: 4

train:
  root: null
  resume_path: null
  global_step: 0

  exp_name: &exp_name clip_1024
  wandb_proj: *exp_name
  output_dir: 0826_hat_clip
  logging_dir: logs
  mixed_precision: bf16
  gradient_accumulation_steps: 1
  report_to: null

  lr: 1e-4
  num_iter: 500000
  save_every: 5000

data:
  wds_path: [/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Long-Caption, /data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Short-Caption, /data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-JourneyDB]
  num_train_examples: 35000000
  img_size: 448
  buffer_size: 10
  batch_size: 5
  num_workers: 8
  cfg_drop_rate: 0.1
  num_img_token: *num_query
  max_seq_length: 512