machine: ks

model:
  num_hat: 8
  stages: [0, 9, 18, 27]

  dit_head:
    in_channels: 1024
    out_channels: 1024
    condition_channels: 3584
    num_tokens: 4

    hidden_size: 2048
    num_heads: 32
    depth: 4

# dit_head:
#   in_channels: 1024
#   out_channels: 1024
#   condition_channels: 1024
#   num_tokens: 4

#   hidden_size: 1024
#   num_heads: 16
#   depth: 16
train:
  root: null
  resume_path: null
  global_step: 0

  exp_name: &exp_name clip_1024
  wandb_proj: *exp_name
  output_dir: 0828_reshat
  logging_dir: logs
  mixed_precision: bf16
  gradient_accumulation_steps: 1
  report_to: wandb

  lr: 1e-4
  num_iter: 500000
  save_every: 10000