machine: ks

model:
  num_hat: 8
  stages: [0, 9, 18, 27]

  dit_head:
    in_channels: 1024
    out_channels: 1024
    condition_channels: 3584
    num_tokens: 4

    hidden_size: 2048
    num_heads: 32
    depth: 4

# dit_head:
#   in_channels: 1024
#   out_channels: 1024
#   condition_channels: 1024
#   num_tokens: 4

#   hidden_size: 1024
#   num_heads: 16
#   depth: 16