machine: "ks"

feature_down_projector:
  clip_feature_dim: 896
  feature_dim_output: 8

train:
  root: null
  resume_path: null
  global_step: 0

  exp_name: &exp_name "mmdit"
  wandb_proj: *exp_name
  output_dir: "0807_aligner_free_intern"
  logging_dir: "logs"
  mixed_precision: "bf16"
  gradient_accumulation_steps: 1
  report_to: "no"

  lr: 1e-4
  num_iter: 100000
  save_every: 5000

data:
  wds_path: ["/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Long-Caption", "/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Short-Caption", "/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-JourneyDB",]
  img_size: 448
  buffer_size: 50000
  batch_size: 25
  num_workers: 8
  num_img_token: 256
  max_seq_length: 512
  cfg_drop_rate: 0.1