machine: "ks"

feature_down_projector:
  clip_feature_dim: 1024
  feature_dim_output: 16
  shuffle: true
  feature_mixer:
    hidden_size: 1024
    depth: 16
    num_heads: 16
    grid_size: 16

base_model: "intern_vl_8b"

train:
  root: null
  resume_path: "/data/phd/jinjiachun/experiment/mmdit/0809_aligner_free_intern_pre_adapter_dim16/mmdit-mmdit-30000"
  global_step: 30000

  exp_name: &exp_name "mmdit"
  wandb_proj: *exp_name
  output_dir: "0810_256x16_feature_mixer"
  logging_dir: "logs"
  mixed_precision: "bf16"
  gradient_accumulation_steps: 1
  report_to: "wandb"

  lr: 1e-4
  num_iter: 200000
  save_every: 5000

data:
  wds_path: ["/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Long-Caption", "/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-Short-Caption", "/data/phd/jinjiachun/dataset/BLIP3o/BLIP3o-Pretrain-JourneyDB",]
  img_size: 448
  buffer_size: 50000
  batch_size: 15
  num_workers: 8
  num_img_token: 256
  max_seq_length: 512
  cfg_drop_rate: 0.1