machine: "g3" # [g3, ks]

vae_aligner:
  pretrained_path: "/data/phd/jinjiachun/experiment/vae_aligner/0706_vae_aligner_hybrid_50M/vae_aligner-vae_aligner-200k"
  hidden_size: 1024
  depth: 16
  num_heads: 16
  grid_size: 24

  siglip_feature_dim: 1024
  siglip_feature_dim_down: 16

query_dit:
  hidden_size: 1024
  num_heads: 16
  depth: 16
  x_dim: 16
  z_dim: 2048

query:
  num_queries: 576
  query_dim: 2048

train:
  root:
  resume_path:
  skipped_keys:
  global_step:

  exp_name: &exp_name "query_dit"
  wandb_proj: *exp_name
  output_dir: "tmp"
  logging_dir: "logs"
  mixed_precision: "bf16"
  gradient_accumulation_steps: 1
  report_to: "no"

  cfg_drop_rate: 0.1

  lr: 1e-4
  num_iter: 50000
  save_every: 10000
  val_every: 100  # 每5000步进行一次验证和采样


data:
  name: "t2i"
  train_path:
  batch_size: 12
  num_workers: 8
  img_size: 192
  streaming: true
  buffer_size: 500
  max_text_length: 192